; ----------------------------------------------------
; GHOST FIRMWARE - UNIFIED TARGET CONFIGURATION
; DEVELOPER: ://instagram.com
; REPOSITORY: ://github.com
; ----------------------------------------------------
[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
build_flags = 
    -D CORE_DEBUG_LEVEL=0

; FIXED: Upgraded library pins to 0.1.17 to resolve core2 include path mapping errors
lib_deps =
    m5stack/M5GFX @ 0.1.17
    m5stack/M5Unified @ 0.1.17

; ----------------------------------------------------
; TARGET 1: M5STACK CARDPUTER (ESP32-S3)
; ----------------------------------------------------
[env:m5stack-cardputer]
board = esp32-s3-devkitc-1
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_M5Stack_Cardputer
    -D CARDPUTER_HARDWARE

; ----------------------------------------------------
; TARGET 2: M5STACK CORE2 (ESP32-D0WDQ6-V3)
; ----------------------------------------------------
[env:m5stack-core2]
board = m5stack-core2
build_flags = 
    ${env.build_flags}
    -D CORE2_HARDWARE

; ----------------------------------------------------
; TARGET 3: M5STICKC PLUS (ESP32-PICO-D4)
; ----------------------------------------------------
[env:m5stick-cplus]
board = m5stick-c
build_flags = 
    ${env.build_flags}
    -D STICKC_PLUS_HARDWARE
